# Generated by Django 4.2.1 on 2023-05-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('titolo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('luogo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('costo_biglietto', models.FloatField()),
                ('num_partecipanti', models.IntegerField()),
                ('posti_disponibili', models.IntegerField()),
                ('orario', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Eventi',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('num_tel', models.IntegerField()),
                ('data_nascita', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('tag_preferiti', models.ManyToManyField(to='EventManager.tag')),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Registrazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utente', models.CharField(max_length=100)),
                ('email_utente', models.EmailField(max_length=254)),
                ('num_tel_utente', models.IntegerField()),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManager.evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='tag',
            field=models.ManyToManyField(to='EventManager.tag'),
        ),
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManager.evento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManager.utente')),
            ],
            options={
                'verbose_name_plural': 'Biglietti',
            },
        ),
    ]
