# Generated by Django 4.2.1 on 2023-06-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0007_alter_evento_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tag',
            field=models.ManyToManyField(related_name='eventi', to='EventManager.tag'),
        ),
    ]
