# Generated by Django 4.2.1 on 2023-06-04 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventManager', '0008_alter_evento_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='iscritti',
            field=models.ManyToManyField(related_name='eventi_iscritti', through='EventManager.Iscrizione', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='iscrizione',
            unique_together={('user', 'evento')},
        ),
    ]
