# Generated by Django 4.2.1 on 2023-06-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0009_evento_iscritti_iscrizione_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iscrizione',
            options={'verbose_name_plural': 'Iscrizioni'},
        ),
        migrations.AlterModelOptions(
            name='registrazione',
            options={'verbose_name_plural': 'Registrazioni'},
        ),
    ]
