# Generated by Django 4.2.1 on 2023-06-05 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventManager', '0011_remove_iscrizione_cognome_remove_iscrizione_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Registrazione',
        ),
    ]
