# Generated by Django 4.2.1 on 2023-06-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0012_evento_creatore_delete_registrazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='programma',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
