# Generated by Django 4.2.1 on 2023-06-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0013_evento_programma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='num_partecipanti',
            new_name='num_max_partecipanti',
        ),
        migrations.DeleteModel(
            name='Biglietto',
        ),
    ]
