# Generated by Django 4.2.1 on 2023-06-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0014_rename_num_partecipanti_evento_num_max_partecipanti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
